---
title: "Updated Figures 3_4_5: map,area,richness"
output: html_notebook
---

Map, area, richness

```{r setup}
library(data.table)
library(ggplot2)
library(cowplot)
library(egg)
library(mapproj)
```

Load data (these files created on annotate (HPC))
```{r load latitude cross area data}
west_pac_shelf_areas <- readRDS(here::here("output","files_back_from_annotate","west_pac_shelf_areas_2degrees.rds"))
west_atl_shelf_areas <- readRDS(here::here("output","files_back_from_annotate","west_atl_shelf_areas_2degrees.rds"))
west_ind_shelf_areas <- readRDS(here::here("output","files_back_from_annotate","west_ind_shelf_areas_2degrees.rds"))
east_pac_shelf_areas <- readRDS(here::here("output","files_back_from_annotate","east_pac_shelf_areas_2degrees.rds"))
east_atl_shelf_areas <- readRDS(here::here("output","files_back_from_annotate","east_atl_shelf_areas_2degrees.rds"))
east_ind_shelf_areas <- readRDS(here::here("output","files_back_from_annotate","east_ind_shelf_areas_2degrees.rds"))

```

```{r load latitude area plots and such}
load(here::here("Figures", "Figure3_5","latitude_area_plots.RData")) #from degree_shifts_projeected_2degrees.Rmd

load(here::here("Figures","Figure3_5", "region_maps.RData")) #maps from degree_shifts_projeected_2degrees.Rmd

load(here::here("Figures","Figure3_5", "latitude_2degree_maps.RData")) #latitude area plots from degree_shifts_projeected_2degrees.Rmd

shelf_areas_fullstats <- readRDS(file = here::here("output","2_degree_latitude","shelf_areas_fullstats.rds")) #spp richness stats from degree_shifts_projeected_2degrees_globalarea.Rmd

#change order of loss gain to allow for correct plotting order
shelf_areas_fullstats[,spp_change_pos_neg_175_discrete:= factor(spp_change_pos_neg_175_discrete, levels = c("Loss","Gain"))][,spp_change_pos_neg_38_discrete:= factor(spp_change_pos_neg_38_discrete, levels = c("Loss","Gain"))][,spp_change_pos_neg_62_discrete:= factor(spp_change_pos_neg_62_discrete, levels = c("Loss","Gain"))]
```


#East Atlantic
```{r east atlantic plots}
#######
##MINIMUM
#######
#min raw value
(east_atlantic_spprichness_min <- ggplot(data = shelf_areas_fullstats[region == "East Atlantic"], aes(x=latitude_start, y=change_spp_predicted_175)) +
   geom_col(aes(fill=spp_change_pos_neg_175_discrete), alpha = 0.5) +
    scale_fill_viridis_d(option = "A", begin = 0.3, end = 0.7, name = "Species Richness Change\nWith 2\u00B0 Latitudinal Shift\nz = 0.175", labels = c("Loss", "Gain")) +
    labs(x = "Depth  (15 m bins)", y = "Change in Spp Richness") +
 labs(x=paste0("Latitude ","\u00B0","N"), y = expression(Delta~'Species Richness')) +
#  scale_x_continuous(expand = c(0, 0)) + #gets rid of gap
#  scale_y_continuous(expand = c(0, 0)) +
  geom_vline(xintercept = 0) +
  coord_flip() +
  theme_classic())

#min percent change value
(east_atlantic_spprichness_min_percentchange <- ggplot(data = shelf_areas_fullstats[region == "East Atlantic"], aes(x=latitude_start, y=percent_change_richness_min*100)) +
   geom_col(aes(fill=spp_change_pos_neg_175_discrete), alpha = 0.5) +
    scale_fill_viridis_d(option = "A", begin = 0.3, end = 0.7, name = " Percent Richness Change\nWith 2\u00B0 Latitudinal Shift\nz = 0.175", labels = c("Loss", "Gain")) +
 labs(x=paste0("Latitude ","\u00B0","N"), y = expression('Percent'~Delta~'Species Richness')) +
#  scale_x_continuous(expand = c(0, 0)) + #gets rid of gap
#  scale_y_continuous(expand = c(0, 0)) +
  geom_vline(xintercept = 0) +
  coord_flip() +
  theme_classic())


#######
##MEAN
#######
#mean raw value
(east_atlantic_spprichness_mean <- ggplot(data = shelf_areas_fullstats[region == "East Atlantic"], aes(x=latitude_start, y=change_spp_predicted_38)) +
   geom_col(aes(fill=spp_change_pos_neg_38_discrete), alpha = 0.5) +
    scale_fill_viridis_d(option = "A", begin = 0.3, end = 0.7, name = "Species Richness Change\nWith 2\u00B0 Latitudinal Shift\nz = 0.38", labels = c("Loss", "Gain")) +
    labs(x = "Depth  (15 m bins)", y = "Change in Spp Richness") +
 labs(x=paste0("Latitude ","\u00B0","N"), y = expression(Delta~'Species Richness')) +
#  scale_x_continuous(expand = c(0, 0)) + #gets rid of gap
#  scale_y_continuous(expand = c(0, 0)) +
  geom_vline(xintercept = 0) +
  coord_flip() +
  theme_classic())

#mean percent change value
(east_atlantic_spprichness_mean_percentchange <- ggplot(data = shelf_areas_fullstats[region == "East Atlantic"], aes(x=latitude_start, y=percent_change_richness_mean*100)) +
   geom_col(aes(fill=spp_change_pos_neg_38_discrete), alpha = 0.5) +
    scale_fill_viridis_d(option = "A", begin = 0.3, end = 0.7, name = " Percent Richness Change\nWith 2\u00B0 Latitudinal Shift\nz = 0.38", labels = c("Loss", "Gain")) +
 labs(x=paste0("Latitude ","\u00B0","N"), y = expression('Percent'~Delta~'Species Richness')) +
#  scale_x_continuous(expand = c(0, 0)) + #gets rid of gap
#  scale_y_continuous(expand = c(0, 0)) +
  geom_vline(xintercept = 0) +
  coord_flip() +
  theme_classic())

#######
##MAXIMUM
#######
#max raw value
(east_atlantic_spprichness_max <- ggplot(data = shelf_areas_fullstats[region == "East Atlantic"], aes(x=latitude_start, y=change_spp_predicted_62)) +
   geom_col(aes(fill=spp_change_pos_neg_62_discrete), alpha = 0.5) +
    scale_fill_viridis_d(option = "A", begin = 0.3, end = 0.7, name = "Species Richness Change\nWith 2\u00B0 Latitudinal Shift\nz = 0.62", labels = c("Loss", "Gain")) +
    labs(x = "Depth  (15 m bins)", y = "Change in Spp Richness") +
 labs(x=paste0("Latitude ","\u00B0","N"), y = expression(Delta~'Species Richness')) +
#  scale_x_continuous(expand = c(0, 0)) + #gets rid of gap
#  scale_y_continuous(expand = c(0, 0)) +
  geom_vline(xintercept = 0) +
  coord_flip() +
  theme_classic())

#max percent change value
(east_atlantic_spprichness_max_percentchange <- ggplot(data = shelf_areas_fullstats[region == "East Atlantic"], aes(x=latitude_start, y=percent_change_richness_max*100)) +
   geom_col(aes(fill=spp_change_pos_neg_62_discrete), alpha = 0.5) +
    scale_fill_viridis_d(option = "A", begin = 0.3, end = 0.7, name = " Percent Richness Change\nWith 2\u00B0 Latitudinal Shift\nz = 0.62", labels = c("Loss", "Gain")) +
 labs(x=paste0("Latitude ","\u00B0","N"), y = expression('Percent'~Delta~'Species Richness')) +
#  scale_x_continuous(expand = c(0, 0)) + #gets rid of gap
#  scale_y_continuous(expand = c(0, 0)) +
  geom_vline(xintercept = 0) +
  coord_flip() +
  theme_classic())


```

#West Atlantic

```{r west atlantic plots}
#######
##MINIMUM
#######
#min raw value
(west_atlantic_spprichness_min <- ggplot(data = shelf_areas_fullstats[region == "West Atlantic"], aes(x=latitude_start, y=change_spp_predicted_175)) +
   geom_col(aes(fill=spp_change_pos_neg_175_discrete), alpha = 0.5) +
    scale_fill_viridis_d(option = "A", begin = 0.3, end = 0.7, name = "Species Richness Change\nWith 2\u00B0 Latitudinal Shift\nz = 0.175", labels = c("Loss", "Gain")) +
    labs(x = "Depth  (15 m bins)", y = "Change in Spp Richness") +
 labs(x=paste0("Latitude ","\u00B0","N"), y = expression(Delta~'Species Richness')) +
#  scale_x_continuous(expand = c(0, 0)) + #gets rid of gap
#  scale_y_continuous(expand = c(0, 0)) +
  geom_vline(xintercept = 0) +
  coord_flip() +
  theme_classic())

#min percent change value
(west_atlantic_spprichness_min_percentchange <- ggplot(data = shelf_areas_fullstats[region == "West Atlantic"], aes(x=latitude_start, y=percent_change_richness_min*100)) +
   geom_col(aes(fill=spp_change_pos_neg_175_discrete), alpha = 0.5) +
    scale_fill_viridis_d(option = "A", begin = 0.3, end = 0.7, name = " Percent Richness Change\nWith 2\u00B0 Latitudinal Shift\nz = 0.175", labels = c("Loss", "Gain")) +
 labs(x=paste0("Latitude ","\u00B0","N"), y = expression('Percent'~Delta~'Species Richness')) +
#  scale_x_continuous(expand = c(0, 0)) + #gets rid of gap
#  scale_y_continuous(expand = c(0, 0)) +
  geom_vline(xintercept = 0) +
  coord_flip() +
  theme_classic())


#######
##MEAN
#######
#mean raw value
(west_atlantic_spprichness_mean <- ggplot(data = shelf_areas_fullstats[region == "West Atlantic"], aes(x=latitude_start, y=change_spp_predicted_38)) +
   geom_col(aes(fill=spp_change_pos_neg_38_discrete), alpha = 0.5) +
    scale_fill_viridis_d(option = "A", begin = 0.3, end = 0.7, name = "Species Richness Change\nWith 2\u00B0 Latitudinal Shift\nz = 0.38", labels = c("Loss", "Gain")) +
    labs(x = "Depth  (15 m bins)", y = "Change in Spp Richness") +
 labs(x=paste0("Latitude ","\u00B0","N"), y = expression(Delta~'Species Richness')) +
#  scale_x_continuous(expand = c(0, 0)) + #gets rid of gap
#  scale_y_continuous(expand = c(0, 0)) +
  geom_vline(xintercept = 0) +
  coord_flip() +
  theme_classic())

#mean percent change value
(west_atlantic_spprichness_mean_percentchange <- ggplot(data = shelf_areas_fullstats[region == "West Atlantic"], aes(x=latitude_start, y=percent_change_richness_mean*100)) +
   geom_col(aes(fill=spp_change_pos_neg_38_discrete), alpha = 0.5) +
    scale_fill_viridis_d(option = "A", begin = 0.3, end = 0.7, name = " Percent Richness Change\nWith 2\u00B0 Latitudinal Shift\nz = 0.38", labels = c("Loss", "Gain")) +
 labs(x=paste0("Latitude ","\u00B0","N"), y = expression('Percent'~Delta~'Species Richness')) +
#  scale_x_continuous(expand = c(0, 0)) + #gets rid of gap
#  scale_y_continuous(expand = c(0, 0)) +
  geom_vline(xintercept = 0) +
  coord_flip() +
  theme_classic())

#######
##MAXIMUM
#######
#max raw value
(west_atlantic_spprichness_max <- ggplot(data = shelf_areas_fullstats[region == "West Atlantic"], aes(x=latitude_start, y=change_spp_predicted_62)) +
   geom_col(aes(fill=spp_change_pos_neg_62_discrete), alpha = 0.5) +
    scale_fill_viridis_d(option = "A", begin = 0.3, end = 0.7, name = "Species Richness Change\nWith 2\u00B0 Latitudinal Shift\nz = 0.62", labels = c("Loss", "Gain")) +
    labs(x = "Depth  (15 m bins)", y = "Change in Spp Richness") +
 labs(x=paste0("Latitude ","\u00B0","N"), y = expression(Delta~'Species Richness')) +
#  scale_x_continuous(expand = c(0, 0)) + #gets rid of gap
#  scale_y_continuous(expand = c(0, 0)) +
  geom_vline(xintercept = 0) +
  coord_flip() +
  theme_classic())

#max percent change value
(west_atlantic_spprichness_max_percentchange <- ggplot(data = shelf_areas_fullstats[region == "West Atlantic"], aes(x=latitude_start, y=percent_change_richness_max*100)) +
   geom_col(aes(fill=spp_change_pos_neg_62_discrete), alpha = 0.5) +
    scale_fill_viridis_d(option = "A", begin = 0.3, end = 0.7, name = " Percent Richness Change\nWith 2\u00B0 Latitudinal Shift\nz = 0.62", labels = c("Loss", "Gain")) +
 labs(x=paste0("Latitude ","\u00B0","N"), y = expression('Percent'~Delta~'Species Richness')) +
#  scale_x_continuous(expand = c(0, 0)) + #gets rid of gap
#  scale_y_continuous(expand = c(0, 0)) +
  geom_vline(xintercept = 0) +
  coord_flip() +
  theme_classic())


```

#Atlantic merge
```{r atlantic merge}
figure_4_atlantic_full <- egg::ggarrange(region_maps[[3]] + 
                                                theme(legend.position = "top",
                                                      axis.title.x = element_blank(),
                                                      plot.margin = unit(c(0.1,0.1,0.1,0.1),"cm")) +
 coord_equal(ylim = c(-55,85), xlim = c(-180,0)) +
                                                scale_y_continuous(breaks = c(-60,-40,-20,0,20,40,60,80)),
          area_latitude_west_atl + 
               theme(axis.text.y = element_blank(),
                    # axis.ticks.y = element_blank(),
                     axis.title.y = element_blank(),
                     axis.title.x = element_blank(),
                     legend.position = "top",
                    legend.text=element_text(size=10),
                    legend.title=element_text(size=10),
                     plot.margin = unit(c(0.1,0.1,0.1,0.1),"cm")) +
      guides(color = guide_legend(title.position = "top", title.hjust = 0.5,direction = "vertical")) +
            xlim(x=c(min(west_atl_shelf_areas$latitude_start),max(west_atl_shelf_areas$latitude_start))) +
                                                scale_x_continuous(breaks = c(-60,-40,-20,0,20,40,60,80)),
          west_atlantic_spprichness_mean_percentchange +
                           theme(axis.text.y = element_blank(),
                    # axis.ticks.y = element_blank(),
                     axis.title.y = element_blank(),
                     axis.title.x = element_blank(),
                    legend.text=element_text(size=10),
                    legend.title=element_text(size=10),
                     plot.margin = unit(c(0.1,0.1,0.1,0.1),"cm"),
                legend.position = "top") +
      guides(fill = guide_legend(title.position = "top", title.hjust = 0.5,direction = "vertical")) +
   xlim(x=c(min(west_atl_shelf_areas$latitude_start),max(west_atl_shelf_areas$latitude_start))) +
                                                scale_x_continuous(breaks = c(-60,-40,-20,0,20,40,60,80)),
 region_maps[[5]] + theme(legend.position = "none",
                                                                          plot.margin = unit(c(0.1,0.1,0.1,0.1),"cm")) +
                                                scale_y_continuous(breaks = c(-40,-20,0,20,40,60,80)) +  coord_equal(ylim = c(-35,81), xlim = c(-20,180)),
          area_latitude_east_atl + 
               theme(axis.text.y = element_blank(),
           #          axis.ticks.y = element_blank(),
                     axis.title.y = element_blank(),
                     legend.position = "none",
                     plot.margin = unit(c(0.1,0.1,0.1,0.1),"cm")) +
                                                scale_x_continuous(breaks = c(-40,-20,0,20,40,60,80)),
          east_atlantic_spprichness_mean_percentchange +
            theme(axis.text.y = element_blank(),
            #    axis.ticks.y = element_blank(),
                axis.title.y = element_blank(),
                plot.margin = unit(c(0.1,0.1,0.1,0.1),"cm"),
                legend.position = "none") +
                                                 scale_x_continuous(breaks = c(-40,-20,0,20,40,60,80)),
 nrow = 2, top = T, bottom = T, widths = c(1,0.7,0.7,1.7,1,1))


figure_4_atlantic_full

ggsave(figure_4_atlantic_full, path = here::here("Figures", "Figure3_5"), filename = "Figure4_atlantic_latitude_area_spprichness.pdf", height = 6, width = 10, unit = "in")
ggsave(figure_4_atlantic_full, path = here::here("Figures", "Figure3_5"), filename = "Figure4_atlantic_latitude_area_spprichness.jpg", height = 6, width = 10, unit = "in")
```


#East pacific
```{r east pacific plots}
#######
##MINIMUM
#######
#min raw value
(east_pacific_spprichness_min <- ggplot(data = shelf_areas_fullstats[region == "East Pacific"], aes(x=latitude_start, y=change_spp_predicted_175)) +
   geom_col(aes(fill=spp_change_pos_neg_175_discrete), alpha = 0.5) +
    scale_fill_viridis_d(option = "A", begin = 0.3, end = 0.7, name = "Species Richness Change\nWith 2\u00B0 Latitudinal Shift\nz = 0.175", labels = c("Loss", "Gain")) +
    labs(x = "Depth  (15 m bins)", y = "Change in Spp Richness") +
 labs(x=paste0("Latitude ","\u00B0","N"), y = expression(Delta~'Species Richness')) +
#  scale_x_continuous(expand = c(0, 0)) + #gets rid of gap
#  scale_y_continuous(expand = c(0, 0)) +
  geom_vline(xintercept = 0) +
  coord_flip() +
  theme_classic())

#min percent change value
(east_pacific_spprichness_min_percentchange <- ggplot(data = shelf_areas_fullstats[region == "East Pacific"], aes(x=latitude_start, y=percent_change_richness_min*100)) +
   geom_col(aes(fill=spp_change_pos_neg_175_discrete), alpha = 0.5) +
    scale_fill_viridis_d(option = "A", begin = 0.3, end = 0.7, name = " Percent Richness Change\nWith 2\u00B0 Latitudinal Shift\nz = 0.175", labels = c("Loss", "Gain")) +
 labs(x=paste0("Latitude ","\u00B0","N"), y = expression('Percent'~Delta~'Species Richness')) +
#  scale_x_continuous(expand = c(0, 0)) + #gets rid of gap
#  scale_y_continuous(expand = c(0, 0)) +
  geom_vline(xintercept = 0) +
  coord_flip() +
  theme_classic())


#######
##MEAN
#######
#mean raw value
(east_pacific_spprichness_mean <- ggplot(data = shelf_areas_fullstats[region == "East Pacific"], aes(x=latitude_start, y=change_spp_predicted_38)) +
   geom_col(aes(fill=spp_change_pos_neg_38_discrete), alpha = 0.5) +
    scale_fill_viridis_d(option = "A", begin = 0.3, end = 0.7, name = "Species Richness Change\nWith 2\u00B0 Latitudinal Shift\nz = 0.38", labels = c("Loss", "Gain")) +
    labs(x = "Depth  (15 m bins)", y = "Change in Spp Richness") +
 labs(x=paste0("Latitude ","\u00B0","N"), y = expression(Delta~'Species Richness')) +
#  scale_x_continuous(expand = c(0, 0)) + #gets rid of gap
#  scale_y_continuous(expand = c(0, 0)) +
  geom_vline(xintercept = 0) +
  coord_flip() +
  theme_classic())

#mean percent change value
(east_pacific_spprichness_mean_percentchange <- ggplot(data = shelf_areas_fullstats[region == "East Pacific"], aes(x=latitude_start, y=percent_change_richness_mean*100)) +
   geom_col(aes(fill=spp_change_pos_neg_38_discrete), alpha = 0.5) +
    scale_fill_viridis_d(option = "A", begin = 0.3, end = 0.7, name = " Percent Richness Change\nWith 2\u00B0 Latitudinal Shift\nz = 0.38", labels = c("Loss", "Gain")) +
 labs(x=paste0("Latitude ","\u00B0","N"), y = expression('Percent'~Delta~'Species Richness')) +
#  scale_x_continuous(expand = c(0, 0)) + #gets rid of gap
#  scale_y_continuous(expand = c(0, 0)) +
  geom_vline(xintercept = 0) +
  coord_flip() +
  theme_classic())

#######
##MAXIMUM
#######
#max raw value
(east_pacific_spprichness_max <- ggplot(data = shelf_areas_fullstats[region == "East Pacific"], aes(x=latitude_start, y=change_spp_predicted_62)) +
   geom_col(aes(fill=spp_change_pos_neg_62_discrete), alpha = 0.5) +
    scale_fill_viridis_d(option = "A", begin = 0.3, end = 0.7, name = "Species Richness Change\nWith 2\u00B0 Latitudinal Shift\nz = 0.62", labels = c("Loss", "Gain")) +
    labs(x = "Depth  (15 m bins)", y = "Change in Spp Richness") +
 labs(x=paste0("Latitude ","\u00B0","N"), y = expression(Delta~'Species Richness')) +
#  scale_x_continuous(expand = c(0, 0)) + #gets rid of gap
#  scale_y_continuous(expand = c(0, 0)) +
  geom_vline(xintercept = 0) +
  coord_flip() +
  theme_classic())

#max percent change value
(east_pacific_spprichness_max_percentchange <- ggplot(data = shelf_areas_fullstats[region == "East Pacific"], aes(x=latitude_start, y=percent_change_richness_max*100)) +
   geom_col(aes(fill=spp_change_pos_neg_62_discrete), alpha = 0.5) +
    scale_fill_viridis_d(option = "A", begin = 0.3, end = 0.7, name = " Percent Richness Change\nWith 2\u00B0 Latitudinal Shift\nz = 0.62", labels = c("Loss", "Gain")) +
 labs(x=paste0("Latitude ","\u00B0","N"), y = expression('Percent'~Delta~'Species Richness')) +
#  scale_x_continuous(expand = c(0, 0)) + #gets rid of gap
#  scale_y_continuous(expand = c(0, 0)) +
  geom_vline(xintercept = 0) +
  coord_flip() +
  theme_classic())
```

#West pacific

```{r west pacific plots}

#######
##MINIMUM
#######
#min raw value
(west_pacific_spprichness_min <- ggplot(data = shelf_areas_fullstats[region == "West Pacific"], aes(x=latitude_start, y=change_spp_predicted_175)) +
   geom_col(aes(fill=spp_change_pos_neg_175_discrete), alpha = 0.5) +
    scale_fill_viridis_d(option = "A", begin = 0.3, end = 0.7, name = "Species Richness Change\nWith 2\u00B0 Latitudinal Shift\nz = 0.175", labels = c("Loss", "Gain")) +
    labs(x = "Depth  (15 m bins)", y = "Change in Spp Richness") +
 labs(x=paste0("Latitude ","\u00B0","N"), y = expression(Delta~'Species Richness')) +
#  scale_x_continuous(expand = c(0, 0)) + #gets rid of gap
#  scale_y_continuous(expand = c(0, 0)) +
  geom_vline(xintercept = 0) +
  xlim(x=c(min(shelf_areas_fullstats[region == "West Pacific"]$latitude_start),max(shelf_areas_fullstats[region == "West Pacific"]$latitude_start))) +
scale_x_continuous(breaks = c(-40,-20,0,20,40,60,80)) +
  coord_flip() +
  theme_classic())

#min percent change value
(west_pacific_spprichness_min_percentchange <- ggplot(data = shelf_areas_fullstats[region == "West Pacific"], aes(x=latitude_start, y=percent_change_richness_min*100)) +
   geom_col(aes(fill=spp_change_pos_neg_175_discrete), alpha = 0.5) +
    scale_fill_viridis_d(option = "A", begin = 0.3, end = 0.7, name = " Percent Richness Change\nWith 2\u00B0 Latitudinal Shift\nz = 0.175", labels = c("Loss", "Gain")) +
 labs(x=paste0("Latitude ","\u00B0","N"), y = expression('Percent'~Delta~'Species Richness')) +
#  scale_x_continuous(expand = c(0, 0)) + #gets rid of gap
#  scale_y_continuous(expand = c(0, 0)) +
  geom_vline(xintercept = 0) +
  xlim(x=c(min(shelf_areas_fullstats[region == "West Pacific"]$latitude_start),max(shelf_areas_fullstats[region == "West Pacific"]$latitude_start))) +
scale_x_continuous(breaks = c(-40,-20,0,20,40,60,80)) +
  coord_flip() +
  theme_classic())


#######
##MEAN
#######
#mean raw value
(west_pacific_spprichness_mean <- ggplot(data = shelf_areas_fullstats[region == "West Pacific"], aes(x=latitude_start, y=change_spp_predicted_38)) +
   geom_col(aes(fill=spp_change_pos_neg_38_discrete), alpha = 0.5) +
    scale_fill_viridis_d(option = "A", begin = 0.3, end = 0.7, name = "Species Richness Change\nWith 2\u00B0 Latitudinal Shift\nz = 0.38", labels = c("Loss", "Gain")) +
    labs(x = "Depth  (15 m bins)", y = "Change in Spp Richness") +
 labs(x=paste0("Latitude ","\u00B0","N"), y = expression(Delta~'Species Richness')) +
#  scale_x_continuous(expand = c(0, 0)) + #gets rid of gap
#  scale_y_continuous(expand = c(0, 0)) +
  geom_vline(xintercept = 0) +
  xlim(x=c(min(shelf_areas_fullstats[region == "West Pacific"]$latitude_start),max(shelf_areas_fullstats[region == "West Pacific"]$latitude_start))) +
scale_x_continuous(breaks = c(-40,-20,0,20,40,60,80)) +
  coord_flip() +
  theme_classic())

#mean percent change value
(west_pacific_spprichness_mean_percentchange <- ggplot(data = shelf_areas_fullstats[region == "West Pacific"], aes(x=latitude_start, y=percent_change_richness_mean*100)) +
   geom_col(aes(fill=spp_change_pos_neg_38_discrete), alpha = 0.5) +
    scale_fill_viridis_d(option = "A", begin = 0.3, end = 0.7, name = " Percent Richness Change\nWith 2\u00B0 Latitudinal Shift\nz = 0.38", labels = c("Loss", "Gain")) +
 labs(x=paste0("Latitude ","\u00B0","N"), y = expression('Percent'~Delta~'Species Richness')) +
#  scale_x_continuous(expand = c(0, 0)) + #gets rid of gap
#  scale_y_continuous(expand = c(0, 0)) +
  geom_vline(xintercept = 0) +
  xlim(x=c(min(shelf_areas_fullstats[region == "West Pacific"]$latitude_start),max(shelf_areas_fullstats[region == "West Pacific"]$latitude_start))) +
  scale_x_continuous(breaks = c(-40,-20,0,20,40,60,80)) +
  coord_flip() +
  theme_classic())

#######
##MAXIMUM
#######
#max raw value
(west_pacific_spprichness_max <- ggplot(data = shelf_areas_fullstats[region == "West Pacific"], aes(x=latitude_start, y=change_spp_predicted_62)) +
   geom_col(aes(fill=spp_change_pos_neg_62_discrete), alpha = 0.5) +
    scale_fill_viridis_d(option = "A", begin = 0.3, end = 0.7, name = "Species Richness Change\nWith 2\u00B0 Latitudinal Shift\nz = 0.62", labels = c("Loss", "Gain")) +
    labs(x = "Depth  (15 m bins)", y = "Change in Spp Richness") +
 labs(x=paste0("Latitude ","\u00B0","N"), y = expression(Delta~'Species Richness')) +
#  scale_x_continuous(expand = c(0, 0)) + #gets rid of gap
#  scale_y_continuous(expand = c(0, 0)) +
  geom_vline(xintercept = 0)  +
  xlim(x=c(min(shelf_areas_fullstats[region == "West Pacific"]$latitude_start),max(shelf_areas_fullstats[region == "West Pacific"]$latitude_start))) +
 scale_x_continuous(breaks = c(-40,-20,0,20,40,60,80)) +
  coord_flip() +
  theme_classic())

#max percent change value
(west_pacific_spprichness_max_percentchange <- ggplot(data = shelf_areas_fullstats[region == "West Pacific"], aes(x=latitude_start, y=percent_change_richness_max*100)) +
   geom_col(aes(fill=spp_change_pos_neg_62_discrete), alpha = 0.5) +
    scale_fill_viridis_d(option = "A", begin = 0.3, end = 0.7, name = " Percent Richness Change\nWith 2\u00B0 Latitudinal Shift\nz = 0.62", labels = c("Loss", "Gain")) +
 labs(x=paste0("Latitude ","\u00B0","N"), y = expression('Percent'~Delta~'Species Richness')) +
#  scale_x_continuous(expand = c(0, 0)) + #gets rid of gap
#  scale_y_continuous(expand = c(0, 0)) +
  geom_vline(xintercept = 0)  +
  xlim(x=c(min(shelf_areas_fullstats[region == "West Pacific"]$latitude_start),max(shelf_areas_fullstats[region == "West Pacific"]$latitude_start))) +
scale_x_continuous(breaks = c(-40,-20,0,20,40,60,80)) +
  coord_flip() +
  theme_classic())



```

#pacific merge
```{r pacific merge}
figure_3_pacific_full <- egg::ggarrange(region_maps[[1]] + ylim(c(min(west_pac_shelf_areas$latitude_end),max(west_pac_shelf_areas$latitude_end))) +
                                                theme(legend.position = "top",
                                                      legend.title = element_blank(),
                                                      axis.title.x = element_blank(),
                                                      plot.margin = unit(c(0.1,0.1,0.1,0.1),"cm")) +
                                          scale_y_continuous(breaks = c(-40,-20,0,20,40,60,80)) +
coord_equal(ylim = c(-43, 78), xlim = c(0,210)),
          area_latitude_west_pac + 
               theme(axis.text.y = element_blank(),
                    # axis.ticks.y = element_blank(),
                     axis.title.y = element_blank(),
                     axis.title.x = element_blank(),
                     legend.position = "top",
                    legend.text=element_text(size=10),
                    legend.title=element_text(size=10),
                     plot.margin = unit(c(0.1,0.1,0.1,0.1),"cm")) +
      guides(color = guide_legend(title.position = "top", title.hjust = 0.5,direction = "vertical")) +
            xlim(x=c(min(west_pac_shelf_areas$latitude_start),max(west_pac_shelf_areas$latitude_start))) +
                                                scale_x_continuous(breaks = c(-40,-20,0,20,40,60,80)),
          west_pacific_spprichness_mean_percentchange +
                           theme(axis.text.y = element_blank(),
                    # axis.ticks.y = element_blank(),
                     axis.title.y = element_blank(),
                     axis.title.x = element_blank(),
                    legend.text=element_text(size=10),
                    legend.title=element_text(size=10),
                     plot.margin = unit(c(0.1,0.1,0.1,0.1),"cm"),
                legend.position = "top") +
      guides(fill = guide_legend(title.position = "top", title.hjust = 0.5,direction = "vertical")) +
   xlim(x=c(min(west_pac_shelf_areas$latitude_start),max(west_pac_shelf_areas$latitude_start))) +
                                                scale_x_continuous(breaks = c(-60,-40,-20,0,20,40,60,80)),
 region_maps[[2]] + theme(legend.position = "none", plot.margin = unit(c(0.1,0.1,0.1,0.1),"cm")) +
                                                scale_y_continuous(breaks = c(-60,-40,-20,0,20,40,60,80)) + coord_equal(ylim = c(-54, 77), xlim = c(160,300)),
          area_latitude_east_pac + 
               theme(axis.text.y = element_blank(),
           #          axis.ticks.y = element_blank(),
                     axis.title.y = element_blank(),
                     legend.position = "none",
                     plot.margin = unit(c(0.1,0.1,0.1,0.1),"cm")) +
                                                scale_x_continuous(breaks = c(-60,-40,-20,0,20,40,60,80)),
          east_pacific_spprichness_mean_percentchange +
            theme(axis.text.y = element_blank(),
            #    axis.ticks.y = element_blank(),
                axis.title.y = element_blank(),
                plot.margin = unit(c(0.1,0.1,0.1,0.1),"cm"),
                legend.position = "none") +
                                                 scale_x_continuous(breaks = c(-60,-40,-20,0,20,40,60,80)),
 nrow = 2, top = T, bottom = T, widths = c(1,0.7,0.7,1.7,1,1))


figure_3_pacific_full

ggsave(figure_3_pacific_full, path = here::here("Figures", "Figure3_5"), filename = "Figure3_pacific_latitude_area_spprichness.pdf", height = 6, width = 10, unit = "in")
ggsave(figure_3_pacific_full, path = here::here("Figures", "Figure3_5"), filename = "Figure3_pacific_latitude_area_spprichness.jpg", height = 6, width = 10, unit = "in")




```


#Indian
##East Indian

```{r east indian plots}
#pull values from maps
west_ind_map <- ggplot_build(region_maps[[4]])
east_ind_map <- ggplot_build(region_maps[[6]])

#######
##MINIMUM
#######
#min raw value
(east_indian_spprichness_min <- ggplot(data = shelf_areas_fullstats[region == "East Indian"], aes(x=latitude_start, y=change_spp_predicted_175)) +
   geom_col(aes(fill=spp_change_pos_neg_175_discrete), alpha = 0.5) +
    scale_fill_viridis_d(option = "A", begin = 0.3, end = 0.7, name = "Species Richness Change\nWith 2\u00B0 Latitudinal Shift\nz = 0.175", labels = c("Loss", "Gain")) +
    labs(x = "Depth  (15 m bins)", y = "Change in Spp Richness") +
 labs(x=paste0("Latitude ","\u00B0","N"), y = expression(Delta~'Species Richness')) +
#  scale_x_continuous(expand = c(0, 0)) + #gets rid of gap
#  scale_y_continuous(expand = c(0, 0)) +
  geom_vline(xintercept = 0) +
  xlim(x=c(min(shelf_areas_fullstats[region == "East Indian"]$latitude_start),max(shelf_areas_fullstats[region == "East Indian"]$latitude_start))) +
  scale_x_continuous(breaks = c(-60,-40,-20,0,20)) +
  coord_flip() +
  theme_classic())

#min percent change value
(east_indian_spprichness_min_percentchange <- ggplot(data = shelf_areas_fullstats[region == "East Indian"], aes(x=latitude_start, y=percent_change_richness_min*100)) +
   geom_col(aes(fill=spp_change_pos_neg_175_discrete), alpha = 0.5) +
    scale_fill_viridis_d(option = "A", begin = 0.3, end = 0.7, name = " Percent Richness Change\nWith 2\u00B0 Latitudinal Shift\nz = 0.175", labels = c("Loss", "Gain")) +
 labs(x=paste0("Latitude ","\u00B0","N"), y = expression('Percent'~Delta~'Species Richness')) +
#  scale_x_continuous(expand = c(0, 0)) + #gets rid of gap
#  scale_y_continuous(expand = c(0, 0)) +
  geom_vline(xintercept = 0) +
  xlim(x=c(min(shelf_areas_fullstats[region == "East Indian"]$latitude_start),max(shelf_areas_fullstats[region == "East Indian"]$latitude_start))) +
  scale_x_continuous(breaks = c(-60,-40,-20,0,20)) +
  coord_flip() +
  theme_classic())


#######
##MEAN
#######
#mean raw value
(east_indian_spprichness_mean <- ggplot(data = shelf_areas_fullstats[region == "East Indian"], aes(x=latitude_start, y=change_spp_predicted_38)) +
   geom_col(aes(fill=spp_change_pos_neg_38_discrete), alpha = 0.5) +
    scale_fill_viridis_d(option = "A", begin = 0.3, end = 0.7, name = "Species Richness Change\nWith 2\u00B0 Latitudinal Shift\nz = 0.38", labels = c("Loss", "Gain")) +
    labs(x = "Depth  (15 m bins)", y = "Change in Spp Richness") +
 labs(x=paste0("Latitude ","\u00B0","N"), y = expression(Delta~'Species Richness')) +
#  scale_x_continuous(expand = c(0, 0)) + #gets rid of gap
#  scale_y_continuous(expand = c(0, 0)) +
  geom_vline(xintercept = 0) +
  xlim(x=c(min(shelf_areas_fullstats[region == "East Indian"]$latitude_start),max(shelf_areas_fullstats[region == "East Indian"]$latitude_start))) +
  scale_x_continuous(breaks = c(-60,-40,-20,0,20)) +
  coord_flip() +
  theme_classic())

#mean percent change value
(east_indian_spprichness_mean_percentchange <- ggplot(data = shelf_areas_fullstats[region == "East Indian"], aes(x=latitude_start, y=percent_change_richness_mean*100)) +
   geom_col(aes(fill=spp_change_pos_neg_38_discrete), alpha = 0.5) +
    scale_fill_viridis_d(option = "A", begin = 0.3, end = 0.7, name = " Percent Richness Change\nWith 2\u00B0 Latitudinal Shift\nz = 0.38", labels = c("Loss", "Gain")) +
 labs(x=paste0("Latitude ","\u00B0","N"), y = expression('Percent'~Delta~'Species Richness')) +
#  scale_x_continuous(expand = c(0, 0)) + #gets rid of gap
#  scale_y_continuous(expand = c(0, 0)) +
  geom_vline(xintercept = 0) +
  xlim(x=c(min(shelf_areas_fullstats[region == "East Indian"]$latitude_start),max(shelf_areas_fullstats[region == "East Indian"]$latitude_start))) +
  scale_x_continuous(breaks = c(-60,-40,-20,0,20)) +
  coord_flip() +
  theme_classic())

#######
##MAXIMUM
#######
#max raw value
(east_indian_spprichness_max <- ggplot(data = shelf_areas_fullstats[region == "East Indian"], aes(x=latitude_start, y=change_spp_predicted_62)) +
   geom_col(aes(fill=spp_change_pos_neg_62_discrete), alpha = 0.5) +
    scale_fill_viridis_d(option = "A", begin = 0.3, end = 0.7, name = "Species Richness Change\nWith 2\u00B0 Latitudinal Shift\nz = 0.62", labels = c("Loss", "Gain")) +
    labs(x = "Depth  (15 m bins)", y = "Change in Spp Richness") +
 labs(x=paste0("Latitude ","\u00B0","N"), y = expression(Delta~'Species Richness')) +
#  scale_x_continuous(expand = c(0, 0)) + #gets rid of gap
#  scale_y_continuous(expand = c(0, 0)) +
  geom_vline(xintercept = 0)  +
  xlim(x=c(min(shelf_areas_fullstats[region == "East Indian"]$latitude_start),max(shelf_areas_fullstats[region == "East Indian"]$latitude_start))) +
  scale_x_continuous(breaks = c(-60,-40,-20,0,20)) +
  coord_flip() +
  theme_classic())

#max percent change value
(east_indian_spprichness_max_percentchange <- ggplot(data = shelf_areas_fullstats[region == "East Indian"], aes(x=latitude_start, y=percent_change_richness_max*100)) +
   geom_col(aes(fill=spp_change_pos_neg_62_discrete), alpha = 0.5) +
    scale_fill_viridis_d(option = "A", begin = 0.3, end = 0.7, name = " Percent Richness Change\nWith 2\u00B0 Latitudinal Shift\nz = 0.62", labels = c("Loss", "Gain")) +
 labs(x=paste0("Latitude ","\u00B0","N"), y = expression('Percent'~Delta~'Species Richness')) +
#  scale_x_continuous(expand = c(0, 0)) + #gets rid of gap
#  scale_y_continuous(expand = c(0, 0)) +
  geom_vline(xintercept = 0)  +
  xlim(x=c(min(shelf_areas_fullstats[region == "East Indian"]$latitude_start),max(shelf_areas_fullstats[region == "East Indian"]$latitude_start))) +
  scale_x_continuous(breaks = c(-60,-40,-20,0,20)) +
  coord_flip() +
  theme_classic())
```
  
  

#West indian

```{r west indian plots}
#######
##MINIMUM
#######
#min raw value
(west_indian_spprichness_min <- ggplot(data = shelf_areas_fullstats[region == "West Indian"], aes(x=latitude_start, y=change_spp_predicted_175)) +
   geom_col(aes(fill=spp_change_pos_neg_175_discrete), alpha = 0.5) +
    scale_fill_viridis_d(option = "A", begin = 0.3, end = 0.7, name = "Species Richness Change\nWith 2\u00B0 Latitudinal Shift\nz = 0.175", labels = c("Loss", "Gain")) +
    labs(x = "Depth  (15 m bins)", y = "Change in Spp Richness") +
 labs(x=paste0("Latitude ","\u00B0","N"), y = expression(Delta~'Species Richness')) +
#  scale_x_continuous(expand = c(0, 0)) + #gets rid of gap
#  scale_y_continuous(expand = c(0, 0)) +
  geom_vline(xintercept = 0) +
  xlim(x=c(min(shelf_areas_fullstats[region == "West Indian"]$latitude_start),max(shelf_areas_fullstats[region == "West Indian"]$latitude_start))) +
  scale_x_continuous(breaks = c(-40,-30,-20,-10,0,10,20,30)) +
  coord_flip() +
  theme_classic())

#min percent change value
(west_indian_spprichness_min_percentchange <- ggplot(data = shelf_areas_fullstats[region == "West Indian"], aes(x=latitude_start, y=percent_change_richness_min*100)) +
   geom_col(aes(fill=spp_change_pos_neg_175_discrete), alpha = 0.5) +
    scale_fill_viridis_d(option = "A", begin = 0.3, end = 0.7, name = " Percent Richness Change\nWith 2\u00B0 Latitudinal Shift\nz = 0.175", labels = c("Loss", "Gain")) +
 labs(x=paste0("Latitude ","\u00B0","N"), y = expression('Percent'~Delta~'Species Richness')) +
#  scale_x_continuous(expand = c(0, 0)) + #gets rid of gap
#  scale_y_continuous(expand = c(0, 0)) +
  geom_vline(xintercept = 0) +
  xlim(x=c(min(shelf_areas_fullstats[region == "West Indian"]$latitude_start),max(shelf_areas_fullstats[region == "West Indian"]$latitude_start))) +
  scale_x_continuous(breaks = c(-40,-30,-20,-10,0,10,20,30)) +
  coord_flip() +
  theme_classic())


#######
##MEAN
#######
#mean raw value
(west_indian_spprichness_mean <- ggplot(data = shelf_areas_fullstats[region == "West Indian"], aes(x=latitude_start, y=change_spp_predicted_38)) +
   geom_col(aes(fill=spp_change_pos_neg_38_discrete), alpha = 0.5) +
    scale_fill_viridis_d(option = "A", begin = 0.3, end = 0.7, name = "Species Richness Change\nWith 2\u00B0 Latitudinal Shift\nz = 0.38", labels = c("Loss", "Gain")) +
    labs(x = "Depth  (15 m bins)", y = "Change in Spp Richness") +
 labs(x=paste0("Latitude ","\u00B0","N"), y = expression(Delta~'Species Richness')) +
#  scale_x_continuous(expand = c(0, 0)) + #gets rid of gap
#  scale_y_continuous(expand = c(0, 0)) +
  geom_vline(xintercept = 0) +
  xlim(x=c(min(shelf_areas_fullstats[region == "West Indian"]$latitude_start),max(shelf_areas_fullstats[region == "West Indian"]$latitude_start))) +
  scale_x_continuous(breaks = c(-40,-30,-20,-10,0,10,20,30)) +
  coord_flip() +
  theme_classic())

#mean percent change value
(west_indian_spprichness_mean_percentchange <- ggplot(data = shelf_areas_fullstats[region == "West Indian"], aes(x=latitude_start, y=percent_change_richness_mean*100)) +
   geom_col(aes(fill=spp_change_pos_neg_38_discrete), alpha = 0.5) +
    scale_fill_viridis_d(option = "A", begin = 0.3, end = 0.7, name = " Percent Richness Change\nWith 2\u00B0 Latitudinal Shift\nz = 0.38", labels = c("Loss", "Gain")) +
 labs(x=paste0("Latitude ","\u00B0","N"), y = expression('Percent'~Delta~'Species Richness')) +
#  scale_x_continuous(expand = c(0, 0)) + #gets rid of gap
#  scale_y_continuous(expand = c(0, 0)) +
  geom_vline(xintercept = 0) +
  xlim(x=c(min(shelf_areas_fullstats[region == "West Indian"]$latitude_start),max(shelf_areas_fullstats[region == "West Indian"]$latitude_start))) +
  scale_x_continuous(breaks = c(-40,-30,-20,-10,0,10,20,30)) +
  coord_flip() +
  theme_classic())

#######
##MAXIMUM
#######
#max raw value
(west_indian_spprichness_max <- ggplot(data = shelf_areas_fullstats[region == "West Indian"], aes(x=latitude_start, y=change_spp_predicted_62)) +
   geom_col(aes(fill=spp_change_pos_neg_62_discrete), alpha = 0.5) +
    scale_fill_viridis_d(option = "A", begin = 0.3, end = 0.7, name = "Species Richness Change\nWith 2\u00B0 Latitudinal Shift\nz = 0.62", labels = c("Loss", "Gain")) +
    labs(x = "Depth  (15 m bins)", y = "Change in Spp Richness") +
 labs(x=paste0("Latitude ","\u00B0","N"), y = expression(Delta~'Species Richness')) +
#  scale_x_continuous(expand = c(0, 0)) + #gets rid of gap
#  scale_y_continuous(expand = c(0, 0)) +
  geom_vline(xintercept = 0)  +
  xlim(x=c(min(shelf_areas_fullstats[region == "West Indian"]$latitude_start),max(shelf_areas_fullstats[region == "West Indian"]$latitude_start))) +
  scale_x_continuous(breaks = c(-40,-30,-20,-10,0,10,20,30)) +
  coord_flip() +
  theme_classic())

#max percent change value
(west_indian_spprichness_max_percentchange <- ggplot(data = shelf_areas_fullstats[region == "West Indian"], aes(x=latitude_start, y=percent_change_richness_max*100)) +
   geom_col(aes(fill=spp_change_pos_neg_62_discrete), alpha = 0.5) +
    scale_fill_viridis_d(option = "A", begin = 0.3, end = 0.7, name = " Percent Richness Change\nWith 2\u00B0 Latitudinal Shift\nz = 0.62", labels = c("Loss", "Gain")) +
 labs(x=paste0("Latitude ","\u00B0","N"), y = expression('Percent'~Delta~'Species Richness')) +
#  scale_x_continuous(expand = c(0, 0)) + #gets rid of gap
#  scale_y_continuous(expand = c(0, 0)) +
  geom_vline(xintercept = 0)  +
  xlim(x=c(min(shelf_areas_fullstats[region == "West Indian"]$latitude_start),max(shelf_areas_fullstats[region == "West Indian"]$latitude_start))) +
  scale_x_continuous(breaks = c(-40,-30,-20,-10,0,10,20,30)) +
  coord_flip() +
  theme_classic())
```
  








#Indian Ocean merge

```{r indian merge}

figure_5_indian_full <- egg::ggarrange(region_maps[[4]] + 
                                                theme(legend.position = "top",
                                                      axis.title.x = element_blank(),
                                                      plot.margin = unit(c(0.1,0.1,0.1,0.1),"cm"))+
   coord_equal(ylim = c(-38,32), xlim = c(10,83)) +
                                                scale_y_continuous(breaks = c(-40,-30,-20,-10,0,10,20,30)),
          area_latitude_west_ind + 
               theme(axis.text.y = element_blank(),
                    # axis.ticks.y = element_blank(),
                     axis.title.y = element_blank(),
                     axis.title.x = element_blank(),
                     legend.position = "top",
                    legend.text=element_text(size=10),
                    legend.title=element_text(size=10),
                     plot.margin = unit(c(0.1,0.1,0.1,0.1),"cm")) +
      guides(color = guide_legend(title.position = "top", title.hjust = 0.5,direction = "vertical")) +
            xlim(min(west_ind_map$data[[1]]$y), max(west_ind_map$data[[1]]$y)) +
                                                scale_x_continuous(breaks = c(-40,-30,-20,-10,0,10,20,30))  +
   xlim(min(west_ind_map$data[[2]]$y), max(west_ind_map$data[[2]]$y)),
          west_indian_spprichness_mean_percentchange +
                           theme(axis.text.y = element_blank(),
                    # axis.ticks.y = element_blank(),
                     axis.title.y = element_blank(),
                     axis.title.x = element_blank(),
                    legend.text=element_text(size=10),
                    legend.title=element_text(size=10),
                     plot.margin = unit(c(0.1,0.1,0.1,0.1),"cm"),
                legend.position = "top") +
      guides(fill = guide_legend(title.position = "top", title.hjust = 0.5,direction = "vertical")) +
                                                scale_x_continuous(breaks = c(-40,-30,-20,-10,0,10,20,30)),
 
 region_maps[[6]] + theme(legend.position = "none",
                          plot.margin = unit(c(0.1,0.1,0.1,0.1),"cm")) +
                                                scale_y_continuous(breaks = c(-40,-20,0,20)) +  coord_equal(ylim = c(-43, 22), xlim = c(74,152)),
          area_latitude_east_ind + 
               theme(axis.text.y = element_blank(),
           #          axis.ticks.y = element_blank(),
                     axis.title.y = element_blank(),
                     legend.position = "none",
                     plot.margin = unit(c(0.1,0.1,0.1,0.1),"cm")) +
                                                scale_x_continuous(breaks = c(-40,-20,0,20)) + xlim(c(-44,22)),
          east_indian_spprichness_mean_percentchange +
            theme(axis.text.y = element_blank(),
            #    axis.ticks.y = element_blank(),
                axis.title.y = element_blank(),
                plot.margin = unit(c(0.1,0.1,0.1,0.1),"cm"),
                legend.position = "none") +
                                                 scale_x_continuous(breaks = c(-60,-40,-20,0,20)) + xlim(c(-44,22)),
 nrow = 2, top = T, bottom = T, left = T, right = T)


figure_5_indian_full

ggsave(figure_5_indian_full, path = here::here("Figures", "Figure3_5"), filename = "Figure5_indian_latitude_area_spprichness.pdf", height = 6, width = 10, unit = "in")
ggsave(figure_5_indian_full, path = here::here("Figures", "Figure3_5"), filename = "Figure5_indian_latitude_area_spprichness.jpg", height = 6, width = 10, unit = "in")

```

##Species Richness Figures For Supplement

Pacific Merge Supplement

```{r pacific Merge min mean max for sup}
figure_3_pacific_full_supplement <- egg::ggarrange(
  #WEST
  #min
          west_pacific_spprichness_min_percentchange +
                           theme(axis.text.y = element_blank(),
                    # axis.ticks.y = element_blank(),
                    # axis.title.y = element_blank(),
                     axis.title.x = element_blank(),
                    legend.text=element_text(size=10),
                    legend.title=element_text(size=10),
                  #   plot.margin = unit(c(0.1,0.1,0.1,0.1),"cm"),
                legend.position = "top") +
      guides(fill = guide_legend(title.position = "top", title.hjust = 0.5,direction = "vertical")) +
        xlab(paste0("West Pacific\n","Latitude ","\u00B0","N")),
      
      #mean
                west_pacific_spprichness_mean_percentchange +
                           theme(axis.text.y = element_blank(),
                    # axis.ticks.y = element_blank(),
                     axis.title.y = element_blank(),
                     axis.title.x = element_blank(),
                    legend.text=element_text(size=10),
                    legend.title=element_text(size=10),
                   #  plot.margin = unit(c(0.1,0.1,0.1,0.1),"cm"),
                legend.position = "top") +
      guides(fill = guide_legend(title.position = "top", title.hjust = 0.5,direction = "vertical")),

      #max
                west_pacific_spprichness_max_percentchange +
                           theme(axis.text.y = element_blank(),
                    # axis.ticks.y = element_blank(),
                     axis.title.y = element_blank(),
                     axis.title.x = element_blank(),
                    legend.text=element_text(size=10),
                    legend.title=element_text(size=10),
                 #    plot.margin = unit(c(0.1,0.1,0.1,0.1),"cm"),
                legend.position = "top") +
      guides(fill = guide_legend(title.position = "top", title.hjust = 0.5,direction = "vertical")),

#EAST
#min
          east_pacific_spprichness_min_percentchange +
            theme(axis.text.y = element_blank(),
            #    axis.ticks.y = element_blank(),
             #   axis.title.y = element_blank(),
              #  plot.margin = unit(c(0.1,0.1,0.1,0.1),"cm"),
                legend.position = "none") +
          xlab(paste0("East Pacific\n","Latitude ","\u00B0","N")),

#mean
          east_pacific_spprichness_mean_percentchange +
            theme(axis.text.y = element_blank(),
            #    axis.ticks.y = element_blank(),
                axis.title.y = element_blank(),
              #  plot.margin = unit(c(0.1,0.1,0.1,0.1),"cm"),
                legend.position = "none"),                                             
#max
          east_pacific_spprichness_max_percentchange +
            theme(axis.text.y = element_blank(),
            #    axis.ticks.y = element_blank(),
                axis.title.y = element_blank(),
              #  plot.margin = unit(c(0.1,0.1,0.1,0.1),"cm"),
                legend.position = "none"),

nrow = 2,ncol = 3, top = T, bottom = T, left = T, right = T)


figure_3_pacific_full_supplement

ggsave(figure_3_pacific_full_supplement, path = here::here("Figures", "Supplement"), filename = "Figure3_pacific_latitude_area_spprichness_supplement.pdf", height = 10, width = 10, unit = "in")
ggsave(figure_3_pacific_full_supplement, path = here::here("Figures", "Supplement"), filename = "Figure3_pacific_latitude_area_spprichness_supplement.jpg", height = 10, width = 10, unit = "in")

```


Atlantic Merge Supplement
```{r atlantic Merge min mean max for sup}
figure_4_atlantic_full_supplement <- egg::ggarrange(
  #WEST
  #min
          west_atlantic_spprichness_min_percentchange +
                           theme(axis.text.y = element_blank(),
                    # axis.ticks.y = element_blank(),
                    # axis.title.y = element_blank(),
                     axis.title.x = element_blank(),
                    legend.text=element_text(size=10),
                    legend.title=element_text(size=10),
                  #   plot.margin = unit(c(0.1,0.1,0.1,0.1),"cm"),
                legend.position = "top") +
      guides(fill = guide_legend(title.position = "top", title.hjust = 0.5,direction = "vertical")) +
        xlab(paste0("West Atlantic\n","Latitude ","\u00B0","N")),
      
      #mean
                west_atlantic_spprichness_mean_percentchange +
                           theme(axis.text.y = element_blank(),
                    # axis.ticks.y = element_blank(),
                     axis.title.y = element_blank(),
                     axis.title.x = element_blank(),
                    legend.text=element_text(size=10),
                    legend.title=element_text(size=10),
                   #  plot.margin = unit(c(0.1,0.1,0.1,0.1),"cm"),
                legend.position = "top") +
      guides(fill = guide_legend(title.position = "top", title.hjust = 0.5,direction = "vertical")),

      #max
                west_atlantic_spprichness_max_percentchange +
                           theme(axis.text.y = element_blank(),
                    # axis.ticks.y = element_blank(),
                     axis.title.y = element_blank(),
                     axis.title.x = element_blank(),
                    legend.text=element_text(size=10),
                    legend.title=element_text(size=10),
                 #    plot.margin = unit(c(0.1,0.1,0.1,0.1),"cm"),
                legend.position = "top") +
      guides(fill = guide_legend(title.position = "top", title.hjust = 0.5,direction = "vertical")),

#EAST
#min
          east_atlantic_spprichness_min_percentchange +
            theme(axis.text.y = element_blank(),
            #    axis.ticks.y = element_blank(),
             #   axis.title.y = element_blank(),
              #  plot.margin = unit(c(0.1,0.1,0.1,0.1),"cm"),
                legend.position = "none") +
          xlab(paste0("East Atlantic\n","Latitude ","\u00B0","N")),

#mean
          east_atlantic_spprichness_mean_percentchange +
            theme(axis.text.y = element_blank(),
            #    axis.ticks.y = element_blank(),
                axis.title.y = element_blank(),
              #  plot.margin = unit(c(0.1,0.1,0.1,0.1),"cm"),
                legend.position = "none"),                                             
#max
          east_atlantic_spprichness_max_percentchange +
            theme(axis.text.y = element_blank(),
            #    axis.ticks.y = element_blank(),
                axis.title.y = element_blank(),
              #  plot.margin = unit(c(0.1,0.1,0.1,0.1),"cm"),
                legend.position = "none"),

nrow = 2,ncol = 3, top = T, bottom = T, left = T, right = T)


figure_4_atlantic_full_supplement

ggsave(figure_4_atlantic_full_supplement, path = here::here("Figures", "Supplement"), filename = "Figure4_atlantic_latitude_area_spprichness_supplement.pdf", height = 10, width = 10, unit = "in")
ggsave(figure_4_atlantic_full_supplement, path = here::here("Figures", "Supplement"), filename = "Figure4_atlantic_latitude_area_spprichness_supplement.jpg", height = 10, width = 10, unit = "in")

```
#Indian Merge for Supplement
```{r indian Merge min mean max for sup}
figure_5_indian_full_supplement <- egg::ggarrange(
  #WEST
  #min
          west_indian_spprichness_min_percentchange +
                           theme(axis.text.y = element_blank(),
                    # axis.ticks.y = element_blank(),
                    # axis.title.y = element_blank(),
                     axis.title.x = element_blank(),
                    legend.text=element_text(size=10),
                    legend.title=element_text(size=10),
                  #   plot.margin = unit(c(0.1,0.1,0.1,0.1),"cm"),
                legend.position = "top") +
      guides(fill = guide_legend(title.position = "top", title.hjust = 0.5,direction = "vertical")) +
                                                scale_x_continuous(breaks = c(-40,-30,-20,-10,0,10,20,30)) +
                xlab(paste0("West Indian\n","Latitude ","\u00B0","N")),
      
      #mean
                west_indian_spprichness_mean_percentchange +
                           theme(axis.text.y = element_blank(),
                    # axis.ticks.y = element_blank(),
                     axis.title.y = element_blank(),
                     axis.title.x = element_blank(),
                    legend.text=element_text(size=10),
                    legend.title=element_text(size=10),
                   #  plot.margin = unit(c(0.1,0.1,0.1,0.1),"cm"),
                legend.position = "top") +
      guides(fill = guide_legend(title.position = "top", title.hjust = 0.5,direction = "vertical")) +
                                                scale_x_continuous(breaks = c(-40,-30,-20,-10,0,10,20,30)),
      
      #max
                west_indian_spprichness_max_percentchange +
                           theme(axis.text.y = element_blank(),
                    # axis.ticks.y = element_blank(),
                     axis.title.y = element_blank(),
                     axis.title.x = element_blank(),
                    legend.text=element_text(size=10),
                    legend.title=element_text(size=10),
                 #    plot.margin = unit(c(0.1,0.1,0.1,0.1),"cm"),
                legend.position = "top") +
      guides(fill = guide_legend(title.position = "top", title.hjust = 0.5,direction = "vertical")) +
                                                scale_x_continuous(breaks = c(-40,-30,-20,-10,0,10,20,30)),
 
#EAST
#min
          east_indian_spprichness_min_percentchange +
            theme(axis.text.y = element_blank(),
            #    axis.ticks.y = element_blank(),
             #   axis.title.y = element_blank(),
              #  plot.margin = unit(c(0.1,0.1,0.1,0.1),"cm"),
                legend.position = "none") +
          xlab(paste0("East Indian\n","Latitude ","\u00B0","N")) +
                                                 scale_x_continuous(breaks = c(-60,-40,-20,0,20)) + xlim(c(-44,22)),

#mean
          east_indian_spprichness_mean_percentchange +
            theme(axis.text.y = element_blank(),
            #    axis.ticks.y = element_blank(),
                axis.title.y = element_blank(),
              #  plot.margin = unit(c(0.1,0.1,0.1,0.1),"cm"),
                legend.position = "none") +                                              scale_x_continuous(breaks = c(-60,-40,-20,0,20)) + xlim(c(-44,22)),

#max
          east_indian_spprichness_max_percentchange +
            theme(axis.text.y = element_blank(),
            #    axis.ticks.y = element_blank(),
                axis.title.y = element_blank(),
              #  plot.margin = unit(c(0.1,0.1,0.1,0.1),"cm"),
                legend.position = "none") +
                                                 scale_x_continuous(breaks = c(-60,-40,-20,0,20)) + xlim(c(-44,22)),

nrow = 2,ncol = 3, top = T, bottom = T, left = T, right = T)


figure_5_indian_full_supplement

ggsave(figure_5_indian_full_supplement, path = here::here("Figures", "Supplement"), filename = "Figure5_indian_latitude_area_spprichness_supplement.pdf", height = 10, width = 10, unit = "in")
ggsave(figure_5_indian_full_supplement, path = here::here("Figures", "Supplement"), filename = "Figure5_indian_latitude_area_spprichness_supplement.jpg", height = 10, width = 10, unit = "in")

```

