---
title: "LME Shelf Bathy Layers"
output: html_notebook
---

```{r setup}
library(data.table)
library(rgdal)
library(raster)
library(rgeos)
library(sp)
```


Download LME Shapefiles from [here](http://lme.edc.uri.edu/index.php/digital-data/113-lme-polygon-boundaries) on October 23, 2020. 

Pulling in LMEs
```{r LMEs}

LME_spdf <- readOGR("LME66/LMEs66.shp")

plot(LME_spdf)

```

Download TOPO1 bedrock grid centered netcdf from [here](https://www.ngdc.noaa.gov/mgg/global/).

```{r opening bathymetry file (very big!)}

r <- raster("ETOPO1_Bed_g_gdal.grd")

r_shelf <- mask
#make mask
r[r>0 ][r<-2000] <- NA

#get rid of all bathy not between 0m and -2000m
```

Clip raster to LMEs (so we only have bathymetry within LMEs)

```{r clip raster to LMEs}
cr <- crop(r, extent(LME_spdf), snap="out")  

fr <- rasterize(LME_spdf, cr)

lr <- mask(x=cr, mask=fr)
```


Continental Shelves

Shelf shapefiles downloaded from [Blue Habitat](bluehabitats.org) May 20th 2020 by Becca Selden.  

```{r continental shelves}
continentalshelf_spdf <- readOGR("Shelf_BlueHabitats/Shelf.shp")
```

************

I should do all of the above myself, but for now, I'll use what Becca sent me!!

```{r pull in beccas file}
etopo_shelf_df <- readRDS("~/Documents/grad school/Rutgers/Repositories/shelf_habitat_distribution/etopo_shelf_df.rds")

head(etopo_shelf_df)

plot(etopo_shelf_df)
```
